[package]
name = "wgpu-webp"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "*"
pollster = "0.2.4"
webp-animation = "0.5.0"
wgpu = { version = "0.11.1", default-features = false }

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 3

